---
hadoop_major_version: 2
hadoop_release: hadoop-2.5.0-cdh5.3.3
hadoop_archive: '{{ hadoop_release }}.tar.gz'
hadoop_sha256: '1c2bd97d9d10f2fc75fc39e3aab0e46ffc969d58a4accb2bc3a6c14b2a502a1c'
hadoop_home_dir: '/home/vagrant/{{ hadoop_release }}'
hadoop_tmp_dir: '/data/hadoop'
hadoop_fs_default_name: 'hdfs://localhost:54310'
