---
hbase_release: hbase-0.96.2
hbase_archive: '{{ hbase_release }}-hadoop{{ hadoop_major_version }}-bin.tar.gz'
hbase_home_dir: '/home/vagrant/{{ hbase_release }}-hadoop{{ hadoop_major_version }}'
hbase_data_dir: /data/hbase
zookeeper_data_dir: /data/zk
