---
hadoop_major_version: 1
hadoop_release: hadoop-1.2.1
hadoop_archive: '{{ hadoop_release }}.tar.gz'
hadoop_home_dir: '/home/vagrant/{{ hadoop_release }}'
hadoop_tmp_dir: '/data/hadoop'
hadoop_fs_default_name: 'hdfs://localhost:54310'
